title: Fernando Cabrera Barranzuela
logo: https://github.com/Ferx096/PORTFOLIO/blob/main/images/fernando.png
description: +51 950988159 | fernandocabrerabrz@gmail.com
show_downloads: true
theme: jekyll-theme-minimal
